Tests for Quality Compliance - Synonyms as classes
edmcouncil/fibo pull request #1131
Opened 2020-08-31 07:30 UTC by mereolog

Signed-off-by: Pawel Garbacz <pawel.garbacz@makolab.com>

## Description

https://github.com/edmcouncil/fibo/blob/master/ONTOLOGY_GUIDE.md#t2-synonyms-as-classes suggests a test to find all equivalent named classes as they may indicate that synonyms were modelled as separated classes, which is not consistent with FIBO conventions.
This pr is to implement this test.

Fixes: #1103

## Checklist:

- [X] I'm familiar with the [FIBO developer quide](../CONTRIBUTING.md#contributing-to-the-fibo-code). My contribution meets all the requirements described there.
- [X] My contribution follows the [principles of best practices for FIBO](../ONTOLOGY_GUIDE.md).
- [X] My changes have been reconciled with latest master and no merge conflicts remain.
- [X] This PR is related to exactly one issue. The issue is referenced by using a GitHub keyword such as "fixes", "closes", or "resolves".
- [X] Hygiene tests have been applied by a PR with "(WIP)" in title.
- [X] The issue has been tested locally using a reasoner (for ontology changes).

2020-09-03 12:38 UTC, przemekgradzki requested changes
@mereolog you must add:

`prefix xsd:   <http://www.w3.org/2001/XMLSchema#>`

After this change, running the hygiene tests generates the following message:

_WARN: Class https://spec.edmcouncil.org/fibo/ontology/FND/Quantities/QuantitiesAndUnits/Rate is modeled as equivalent to https://spec.edmcouncil.org/fibo/ontology/FND/Utilities/Analytics/Ratio - this may indicate polysemy management that is not complient with FIBO_

2020-09-04 06:49 UTC, trypuz approved these changes
Approved

2020-09-04 06:49 UTC, trypuz commented on etc/testing/hygiene/testHygiene1103.sparql
> +  FILTER NOT EXISTS {?class1 owl:deprecated "true"^^xsd:boolean}
Please add a prefix to XSD space

2020-09-04 06:58 UTC, trypuz approved these changes
Approved

2020-09-04 07:43 UTC, przemekgradzki approved these changes
OK

2020-09-04 07:49 UTC, merged