BE-226 - Additional refinement is needed regarding merchants and merchant category codes
edmcouncil/fibo pull request #1176
Opened 2020-09-24 01:27 UTC by ElisaKendall

Signed-off-by: Elisa Kendall <ekendall@thematix.com>

## Description

Refined definitions to address feedback on FBC-260 with respect to merchants and merchant codes, clarifying definitions, adding notes, and eliminating a redundant property

Fixes: #1175 / BE-226

## Checklist:

- [x] I'm familiar with the [FIBO developer quide](../CONTRIBUTING.md#contributing-to-the-fibo-code). My contribution meets all the requirements described there.
- [x] My contribution follows the [principles of best practices for FIBO](../ONTOLOGY_GUIDE.md).
- [x] My changes have been reconciled with latest master and no merge conflicts remain.
- [x] This PR is related to exactly one issue. The issue is referenced by using a GitHub keyword such as "fixes", "closes", or "resolves".
- [x] Hygiene tests have been applied by a PR with "(WIP)" in title.
- [x] The issue has been tested locally using a reasoner (for ontology changes).

2020-09-24 19:02 UTC, dsnewman submitted a review, later dismissed

2020-09-25 01:28 UTC, rivettp requested changes
The definition of Merchant is imprecise and contradicted by its explanatoryNote. 
To be honest I'm not sure why FIBO needs it - if it's just for the domain of a MerchantCode then make that the basis of the definition - since it's outside the concern of FIBO to determine which businesses are eligible for a code. You could just define it as "business that makes sales and is eligible to accept payments by payment card or equivalent".
I think the area of Merchant Code Schemes is a lot more complex than indicated - and could involve jurisdiction or organization-specific extensions and mappings between those and Transaction Codes. Whether we care about that is unclear: we don't have a well-defined use case. If we want people to be able to search for card products by what categories they provide extra spending points then we probably have enough and we would not even need Merchant. If we ALSO want to be able to search against specific merchants where they could receive such extra points, then we'd need more, but IMO that would make it more of a Retail ontology.

2020-09-25 02:34 UTC, ElisaKendall commented on BE/FunctionalEntities/FunctionalEntities.rdf
> +		<fibo-fnd-utl-av:explanatoryNote>The U.S. Uniform Commercial Code (UCC, section 2-104) defines a merchant as a party that &apos;deals in goods of the kind or otherwise by his occupation holds himse
I'll remove the explanatory note.  The definition is exactly what you find in almost every dictionary you look at, however.  TA farmer is not a merchant unless they purchase food items from other farmers and sell them.  In their role of purchasing something someone else produced and reselling it they could be a merchant, but not just selling their own stuff at say a farmer's market.  A craftsperson selling things they have made is not a merchant by the same definition.  Consultants are not merchants.  Day traders are trading on their own behalf and are therefore not merchants.

2020-09-25 02:37 UTC, ElisaKendall commented on BE/FunctionalEntities/FunctionalEntities.rdf
> +		<rdfs:subClassOf rdf:resource="&fibo-fnd-arr-cls;IndustrySectorClassificationScheme"/>
No - they all use the ISO standard.  Mastercard may extend it, but the processors that WF and other banks use to process credit cards via these networks use the ISO codes, not only for consumer cards but for wholesale credit card activities.

This is something that is essential for not only the generic credit card content for schema.org but for potential use by retail as well, who also want this.

2020-09-25 06:26 UTC, rivettp approved these changes
OK, but I remain concerned that we're continuing to make extensions without any semblance of use cases, competency questions, examples or tests.

2020-09-25 11:30 UTC, trypuz approved these changes
Approved

2020-09-25 11:31 UTC, merged