BE-230 - The representation of beneficial owner is incomplete
edmcouncil/fibo pull request #1263
Opened 2020-12-19 00:25 UTC by ElisaKendall

Signed-off-by: Elisa Kendall <ekendall@thematix.com>

## Description

Augmented the definition of beneficial owner to incorporate the situation (allowing representation of ownership percentage and time frame) as well as properties connection the owner to the thing they control in that situation

Fixes: #1262 / BE-230

## Checklist:

- [x] I'm familiar with the [FIBO developer quide](https://github.com/edmcouncil/fibo/blob/master/CONTRIBUTING.md#contributing-to-the-fibo-code). My contribution meets all the requirements described there.
- [x] My contribution follows the [principles of best practices for FIBO](https://github.com/edmcouncil/fibo/blob/master/ONTOLOGY_GUIDE.md).
- [x] My changes have been reconciled with latest master and no merge conflicts remain.
- [x] This PR is related to exactly one issue. The issue is referenced by using a GitHub keyword such as "fixes", "closes", or "resolves".
- [x] Hygiene tests have been applied by a PR with "(WIP)" in title.
- [x] The issue has been tested locally using a reasoner (for ontology changes).

2020-12-20 09:12 UTC, rivettp requested changes
A big question is whether we take the definition from FATF (International Task Force for Money Laundering) that a BeneficialOwner must be a NaturalPerson.

Will help determine whether any Ownership is also normally a BeneficialOwnership? When would it not be? Don't we need to reclassify existing examples such as &fibo-fbc-fct-usind;CitibankNAOwnership which is currently a DirectConsolidation?
When there's a separate RegisteredOwner? How would that situation be modeled?

Generally there are many similar-named properties. It screams out for an example of how this is supposed to be used.

Overall, without examples, it's unclear how this would all be practically used for real.

2020-12-20 19:08 UTC, ElisaKendall commented on BE/OwnershipAndControl/CorporateOwnership.rdf
> +		<skos:definition>indicates the party that retains rights in the asset they control in a beneficial ownership situation</skos:definition>
Beneficial ownership is indirect.  So if someone transfers legal ownership, whether that is through a custodial relationship or some other reason, they keep (retain) the rights they had in the asset.

2020-12-20 19:09 UTC, ElisaKendall commented on BE/OwnershipAndControl/CorporateOwnership.rdf
> +		<fibo-fnd-utl-av:explanatoryNote>From World Bank Report: In identifying the beneficial owner, the focus should be on two factors: the control exercised and the benefit derived. Control of a corpora
done.  and I added a restriction for has identity legally competent natural person

2020-12-20 19:09 UTC, ElisaKendall commented on BE/OwnershipAndControl/CorporateOwnership.rdf
> +		<fibo-fnd-utl-av:explanatoryNote>Beneficial ownership may be shared among a group of individuals. If a beneficial owner controls a position of more than 5 percent in the United States, it must file
dome

2020-12-20 20:24 UTC, jfgemski approved these changes

2020-12-21 17:58 UTC, dsnewman approved these changes

2020-12-22 00:02 UTC, merged