IND-107 - The definition of 'market rate' should not incorporate the concept of a market trend
edmcouncil/fibo pull request #1517
Opened 2021-05-11 23:27 UTC by ElisaKendall

Signed-off-by: Elisa Kendall <ekendall@thematix.com>

## Description

Revised the definition of market rate to read 'rate that represents a ratio value established in the marketplace for' ... per FCT discussion

Fixes: #1515 / IND-107

## Checklist:

- [x] I'm familiar with the [FIBO developer quide](https://github.com/edmcouncil/fibo/blob/master/CONTRIBUTING.md#contributing-to-the-fibo-code). My contribution meets all the requirements described there.
- [x] My contribution follows the [principles of best practices for FIBO](https://github.com/edmcouncil/fibo/blob/master/ONTOLOGY_GUIDE.md).
- [x] My changes have been reconciled with latest master and no merge conflicts remain.
- [x] This PR is related to exactly one issue. The issue is referenced by using a GitHub keyword such as "fixes", "closes", or "resolves".
- [x] Hygiene tests have been applied by a PR with "(WIP)" in title.
- [x] The issue has been tested locally using a reasoner (for ontology changes).

2021-05-12 08:05 UTC, rivettp requested changes
I don't think a market rate necessarily represents a ratio. SO the superclass as well as the definition should change. For example the DJIA is merely the addition of the share prices with a consistency multiplier on the total.

2021-05-12 14:19 UTC, ElisaKendall commented
@rivettp I thought you agreed to this during our meeting - I implemented what we had in the minutes.  DJIA may have a denominator of 1, but a rate is still a rate where rate is a synonym of ratio.

2021-05-12 15:05 UTC, ElisaKendall commented
@rivettp The alternative is to say that something is numeric index value, which we also have in the ontology as a direct subclass of quantity value and as a sibling of market rate but not a subclass of ratio value.  So we could change the examples for DJIA to say that it is a numeric index value rather than a market rate, if that's what you are concerned about, but a rate is a ratio by definition.

2021-05-13 01:01 UTC, rivettp commented
It's market rate that I don't think should be a ratio

2021-05-13 01:27 UTC, ElisaKendall commented
@rivettp Yes, I understand that.  The question is why -  we discussed this on our call and everyone else agreed that it should be.  A rate is a synonym of ratio.  A market rate is a rate.  One could argue that the DJIA is neither a rate nor an average, and that the value of the DJIA should be expressed as an instance of numeric index value rather than of market rate.  I would rather make that change than say that a market rate is not a rate.  Maybe I've misunderstood - are you saying that market rate is not a rate at all, but rather a synonym of 'going rate', which is a monetary amount / price? Currently our subclasses of market rate include quoted exchange rates, yield, interest rate, rate of return, etc.  These are all clearly ratio values, and their definitions correspond to the definition of market rate as we currently have it.  Some indices may have values expressed as market rates and others as numeric index values.  I think that's where we have an issue, which is that the value of the DJIA in our examples is an instance of market rate and should be an instance of numeric index value, but that doesn't mean that market rate should not be defined as a ratio (i.e., as a rate).

2021-05-13 19:24 UTC, jfgemski approved these changes

2021-05-14 17:30 UTC, tahoeblue approved these changes

2021-05-14 21:41 UTC, dallemang approved these changes

2021-05-16 20:45 UTC, merged