FBC-281 - The restriction on exchange that says it operates in exactly 1 municipality is too narrow
edmcouncil/fibo pull request #1536
Opened 2021-06-07 19:29 UTC by ElisaKendall

Signed-off-by: Elisa Kendall <ekendall@thematix.com>

## Description

Modified the markets ontology to loosen constraints on the location in which a given exchange operates, given that there are cases when an exchange may operate in multiple locations, and to allow an exchange name to be multilingual or expressed in a language other than English

Fixes: #1532 / FBC-281

## Checklist:

- [x] I'm familiar with the [FIBO developer quide](https://github.com/edmcouncil/fibo/blob/master/CONTRIBUTING.md#contributing-to-the-fibo-code). My contribution meets all the requirements described there.
- [x] My contribution follows the [principles of best practices for FIBO](https://github.com/edmcouncil/fibo/blob/master/ONTOLOGY_GUIDE.md).
- [x] My changes have been reconciled with latest master and no merge conflicts remain.
- [x] This PR is related to exactly one issue. The issue is referenced by using a GitHub keyword such as "fixes", "closes", or "resolves".
- [x] Hygiene tests have been applied by a PR with "(WIP)" in title.
- [x] The issue has been tested locally using a reasoner (for ontology changes).

2021-06-07 19:57 UTC, rivettp requested changes
I don't like the idea of the extra dependency on Agents. Why is something so generic as Text defined there?

2021-06-07 23:51 UTC, ElisaKendall commented
@rivettp Should it be in its own ontology with only the datatype and related property definition?  Otherwise agents seemed the logical place to include it as the first place it is used.

2021-06-09 17:00 UTC, ElisaKendall commented
@rivettp I've removed the dependency on agents per your request, and will further simplify the change related to the Text datatype in a new update to the issue raised in #1533, so that we avoid some of the challenges in Protege / Pellet, but allow people to use the new datatype as needed in applications that understand RDF 1.1.  I'm currently testing that in a couple of other tools.

2021-06-10 17:30 UTC, jfgemski approved these changes

2021-06-11 06:19 UTC, mereolog commented
@rivettp given [Elisa's change](https://github.com/edmcouncil/fibo/pull/1536#issuecomment-857870843) would you mind re-reviewing this PR?

2021-06-14 08:44 UTC, merged