DER-107 - Need an additional note on bullion to explain the difference between coins that are numismatic (collectible) that have additional value and bullion
edmcouncil/fibo pull request #1580
Opened 2021-09-08 00:13 UTC by ElisaKendall

Signed-off-by: Elisa Kendall <ekendall@thematix.com>

## Description

Added an explanatory note and example to the definition of bullion per FCT discussion

Fixes: #1579 / DER-107

## Checklist:

- [x] I'm familiar with the [FIBO developer quide](https://github.com/edmcouncil/fibo/blob/master/CONTRIBUTING.md#contributing-to-the-fibo-code). My contribution meets all the requirements described there.
- [x] My contribution follows the [principles of best practices for FIBO](https://github.com/edmcouncil/fibo/blob/master/ONTOLOGY_GUIDE.md).
- [x] My changes have been reconciled with latest master and no merge conflicts remain.
- [x] This PR is related to exactly one issue. The issue is referenced by using a GitHub keyword such as "fixes", "closes", or "resolves".
- [x] Hygiene tests have been applied by a PR with "(WIP)" in title.
- [x] The issue has been tested locally using a reasoner (for ontology changes).

2021-09-08 16:56 UTC, jfgemski approved these changes

2021-09-08 19:08 UTC, rivettp requested changes
I dug a bit more and hit some showstoppers marked with *
* This is odd: this page https://www.usmint.gov/coins/coin-medal-programs/american-eagle/gold-bullion describes the "bullion coins" as 91.67% gold! So they would definitely not be eligible

OTOH Buffalo coins are 99.99% gold. IOW there are different kinds of gold coin minted. Though I don't think it's helpful to try to enumerate them, or their weights

* The note uses "eligible" but does not say eligible for what: a delivery for a futures contract? 

It's the US Mint not Treasury Dept that mints coins surely?

Investopedia has "For collectors, bullion coins can be prized for their rarity and aesthetic beauty, which can often cause their value to increase relative to the base value of their precious metals content. This subjective value is known as the "numismatic value" of bullion coins, whereas the value solely attributed to their precious metals content is known as their "melt value." "

* So we could say that coins of sufficient purity could be eligible for a delivery for futures contract but only at their melt value

Not for this issue but how would we represent an asset, and its value, that is a (number of) numismatic coin(s) of bullion quality? Not as a commodity, I know, but as an asset it could, for example, be used as collateral for a loan.

2021-09-14 15:31 UTC, jfgemski approved these changes

2021-09-16 01:05 UTC, rivettp approved these changes

2021-09-16 01:06 UTC, merged