SEC-68 - The definition of bill of exchange needs clarification
edmcouncil/fibo pull request #1582
Opened 2021-09-13 18:29 UTC by ElisaKendall

Signed-off-by: Elisa Kendall <ekendall@thematix.com>

## Description

Clarified the definition of a bill of exchange, including (1) moving it up the hierarchy to a subclass of tradable debt instrument, adding an explanatory note and a synonym of 'bank draft', and (2) revising the definition of bankers' acceptance to say that it is both a bill of exchange and a fixed income security, which a bill of exchange may or may not be

Fixes: #ISSUE_NUMBER

## Checklist:

- [x] I'm familiar with the [FIBO developer quide](https://github.com/edmcouncil/fibo/blob/master/CONTRIBUTING.md#contributing-to-the-fibo-code). My contribution meets all the requirements described there.
- [x] My contribution follows the [principles of best practices for FIBO](https://github.com/edmcouncil/fibo/blob/master/ONTOLOGY_GUIDE.md).
- [x] My changes have been reconciled with latest master and no merge conflicts remain.
- [x] This PR is related to exactly one issue. The issue is referenced by using a GitHub keyword such as "fixes", "closes", or "resolves".
- [x] Hygiene tests have been applied by a PR with "(WIP)" in title.
- [x] The issue has been tested locally using a reasoner (for ontology changes).

2021-09-13 19:51 UTC, jfgemski submitted a review, later dismissed

2021-09-16 01:13 UTC, rivettp requested changes
I think we should tweak this as it;s Production

2021-09-16 01:13 UTC, rivettp commented on SEC/Debt/TradedShortTermDebt.rdf
> +		<skos:definition xml:lang="en">short-term debt instrument issued by a company that is guaranteed by a commercial bank</skos:definition>
ambiguous whether it's the company or the instrument that's guaranteed.
More importantly I believe the bank not only guarantees the payment but is actually responsible for making the payment

2021-09-16 01:13 UTC, rivettp commented on SEC/Debt/TradedShortTermDebt.rdf
> +		<rdfs:subClassOf rdf:resource="&fibo-sec-dbt-dbti;TradableDebtInstrument"/>
we still need to address the redundancy that we have TradableX (class) and isNegotiable (boolean property) when they mean the same thing. That would make sense as a separate issue but we'd need to reflect the choice here.

2021-09-16 16:38 UTC, jfgemski approved these changes

2021-09-17 21:54 UTC, rivettp approved these changes

2021-09-17 22:42 UTC, jfgemski approved these changes

2021-09-20 07:46 UTC, merged