SEC-166 - Need to review the definition of depositary receipt in order to cover variable interest entities
edmcouncil/fibo pull request #1712
Opened 2022-01-28 23:41 UTC by ElisaKendall

Signed-off-by: Elisa Kendall <ekendall@thematix.com>

## Description

Revised the definition of depositary receipt to broaden explanatory notes allowing for inclusion of Chinese ADRs

Fixes: #1711 / SEC-166

## Checklist:

- [x] I'm familiar with the [FIBO developer quide](https://github.com/edmcouncil/fibo/blob/master/CONTRIBUTING.md#contributing-to-the-fibo-code). My contribution meets all the requirements described there.
- [x] My contribution follows the [principles of best practices for FIBO](https://github.com/edmcouncil/fibo/blob/master/ONTOLOGY_GUIDE.md).
- [x] My changes have been reconciled with latest master and no merge conflicts remain.
- [x] This PR is related to exactly one issue. The issue is referenced by using a GitHub keyword such as "fixes", "closes", or "resolves".
- [x] Hygiene tests have been applied by a PR with "(WIP)" in title.
- [x] The issue has been tested locally using a reasoner (for ontology changes).

2022-01-29 19:47 UTC, jfgemski approved these changes

2022-01-31 09:49 UTC, mereolog approved these changes

2022-01-31 09:57 UTC, rivettp requested changes
I don't see that this in any way covers, or even allows for, ADRs for Chinese companies which use a VIE rather than a custodian bank, and have distinct associated risks. I provided a link.

2022-01-31 15:39 UTC, rivettp approved these changes
OK we now have #175 to cover VIEs

2022-01-31 15:40 UTC, merged