DER-124 - Need to address gaps with respect to the CFI representation of swaps
edmcouncil/fibo pull request #1733
Opened 2022-02-15 17:44 UTC by ElisaKendall

Signed-off-by: Elisa Kendall <ekendall@thematix.com>

## Description

Added the concept of a rates swap and the corresponding rate-based leg to the swaps ontology and integrated it with the relevant subordinate ontologies to facilitate mapping to the CFI standard

Fixes: #1727 / DER-124

## Checklist:

- [x] I'm familiar with the [FIBO developer quide](https://github.com/edmcouncil/fibo/blob/master/CONTRIBUTING.md#contributing-to-the-fibo-code). My contribution meets all the requirements described there.
- [x] My contribution follows the [principles of best practices for FIBO](https://github.com/edmcouncil/fibo/blob/master/ONTOLOGY_GUIDE.md).
- [x] My changes have been reconciled with latest master and no merge conflicts remain.
- [x] This PR is related to exactly one issue. The issue is referenced by using a GitHub keyword such as "fixes", "closes", or "resolves".
- [x] Hygiene tests have been applied by a PR with "(WIP)" in title.
- [x] The issue has been tested locally using a reasoner (for ontology changes).

2022-02-26 00:01 UTC, tahoeblue approved these changes

2022-03-14 15:27 UTC, jfgemski submitted a review, later dismissed

2022-03-15 00:01 UTC, rivettp requested changes
The only significant comment for this PR is on the inadequate cardinality e.g. on RateSwap.
Also EquityVolatilitySwap is underspecified.

2022-03-15 15:12 UTC, ElisaKendall commented on DER/DerivativesContracts/CurrencyContracts.rdf
> +		<skos:definition xml:lang="en">foreign exchange agreement between two parties involving both an exchange of two currencies on the spot settlement date at a fixed rate that is agreed upon at the inc
The dates are associated with the legs of the contract.  The definition of currency spot contract has an execution date.  The forward contract also has settlement terms associated with it that include a settlement date, so we are covered there.

2022-03-15 15:16 UTC, ElisaKendall commented on DER/DerivativesContracts/Swaps.rdf
> +		<rdfs:subClassOf rdf:resource="&fibo-der-drc-swp;SwapLeg"/>
SO what are you looking for here?  Do you want the restriction on the leg removed, saying that it is a leg of a swap?  Isn't that part of the definition of "leg"?  The rest of its definition is consistent with the notion of a cashflow, although a leg may or may not take on the structure of a standalone contract.

2022-03-15 15:36 UTC, ElisaKendall commented on DER/DerivativesContracts/Swaps.rdf
> +		<fibo-fnd-utl-av:adaptedFrom>ISO 10962, Securities and related financial instruments - Classification of financial instruments (CFI) code, Fourth edition, 2019-10</fibo-fnd-utl-av:adaptedFrom>
done.

2022-03-15 15:36 UTC, ElisaKendall commented on DER/RateDerivatives/IRSwaps.rdf
> +		<fibo-fnd-utl-av:adaptedFrom xml:lang="en">ISO 10962, Securities and related financial instruments - Classification of financial instruments (CFI) code, Fourth Edition, 2019-10.</fibo-fnd-utl-av:ad
done

2022-03-15 15:41 UTC, ElisaKendall commented on DER/RateDerivatives/IRSwaps.rdf
> +				<owl:someValuesFrom rdf:resource="&fibo-der-rtd-irswp;OvernightRateIndexLeg"/>
No - it's only one leg that is an overnight rate.

2022-03-15 15:43 UTC, ElisaKendall commented on DER/SecurityBasedDerivatives/EquitySwaps.rdf
> +		<skos:definition xml:lang="en">equity swap whose return leg underlier is an equity observable</skos:definition>
ignored per your feedback on the DER call

2022-03-15 15:49 UTC, ElisaKendall commented on DER/SecurityBasedDerivatives/EquitySwaps.rdf
> +		<skos:definition xml:lang="en">swap whose payments are linked to the change in value of an underlying equity (e.g. shares, basket of equities or index).</skos:definition>
added "or its cashflow" to the definition

2022-03-15 15:55 UTC, ElisaKendall commented on DER/SecurityBasedDerivatives/EquitySwaps.rdf
> +		<fibo-fnd-utl-av:explanatoryNote xml:lang="en">An equity volatility swap is a forward swap whose payments depend on the variability of movements in a security or underlying instrument&apos;s price;
changed per discussion

2022-03-15 17:59 UTC, jfgemski approved these changes

2022-03-15 19:37 UTC, rivettp approved these changes
I think some cardinality restrictions are not precise enough but OK to defer.

2022-03-15 19:37 UTC, rivettp commented on DER/DerivativesContracts/Swaps.rdf
> +		<rdfs:subClassOf rdf:resource="&fibo-der-drc-swp;SwapLeg"/>
We should discuss with Jeff independent of this PR

2022-03-15 19:37 UTC, rivettp commented on DER/DerivativesContracts/Swaps.rdf
> +				<owl:someValuesFrom rdf:resource="&fibo-der-drc-swp;RatesSwap"/>
Odd to have the upward restriction, which we don't for other legs. Also the cardinality seems wrong - sure it should be exactly 1 (a given leg cannot be part of many swaps).

2022-03-15 19:37 UTC, rivettp commented on DER/DerivativesContracts/Swaps.rdf
> +				<owl:someValuesFrom rdf:resource="&fibo-der-rtd-rtd;RateBasedObservable"/>
exactly 1 surely

2022-03-15 19:37 UTC, rivettp commented on DER/RateDerivatives/IRSwaps.rdf
> +				<owl:someValuesFrom rdf:resource="&fibo-der-rtd-irswp;OvernightRateIndexLeg"/>
Ok it's not exactly 2 but it cannot be more than 2.

2022-03-15 19:37 UTC, rivettp commented on DER/RateDerivatives/IRSwaps.rdf
> +				<owl:someValuesFrom rdf:resource="&fibo-ind-ir-ir;OvernightRate"/>
exactly 1 for a single leg

2022-03-15 19:37 UTC, rivettp commented on DER/SecurityBasedDerivatives/EquitySwaps.rdf
> +				<owl:someValuesFrom rdf:resource="&fibo-der-sbd-sbd;EquityObservable"/>
exactly 1

2022-03-15 19:37 UTC, rivettp commented on DER/SecurityBasedDerivatives/EquitySwaps.rdf
> +				<owl:someValuesFrom rdf:resource="&fibo-der-sbd-eqs;EquityReturnLeg"/>
exactly 1

2022-03-16 07:24 UTC, merged