FND-364 - Income should be a child of monetary amount rather than have some oblique relationship with monetary amount
edmcouncil/fibo pull request #1758
Opened 2022-03-30 19:00 UTC by ElisaKendall

Signed-off-by: Elisa Kendall <ekendall@thematix.com>

## Description

Modified accounting equity to make income a subclass of monetary amount and eliminate the oblique restriction on monetary amount to simplify its representation

Fixes: #1757 / FND-364

## Checklist:

- [x] I'm familiar with the [FIBO developer quide](https://github.com/edmcouncil/fibo/blob/master/CONTRIBUTING.md#contributing-to-the-fibo-code). My contribution meets all the requirements described there.
- [x] My contribution follows the [principles of best practices for FIBO](https://github.com/edmcouncil/fibo/blob/master/ONTOLOGY_GUIDE.md).
- [x] My changes have been reconciled with latest master and no merge conflicts remain.
- [x] This PR is related to exactly one issue. The issue is referenced by using a GitHub keyword such as "fixes", "closes", or "resolves".
- [x] Hygiene tests have been applied by a PR with "(WIP)" in title.
- [x] The issue has been tested locally using a reasoner (for ontology changes).

2022-03-30 19:44 UTC, jfgemski approved these changes

2022-03-30 20:13 UTC, tahoeblue approved these changes

2022-03-30 21:59 UTC, rivettp requested changes
Not at all sure about this change - I don't think you could substitute an instance of Income wherever MonetaryAmount appears e.g. as the price of an equity.

2022-03-30 22:20 UTC, jfgemski approved these changes

2022-03-30 22:51 UTC, ElisaKendall commented
> Not at all sure about this change - I don't think you could substitute an instance of Income wherever MonetaryAmount appears e.g. as the price of an equity.

That's not what this does - it says that Income is  a subclass of MonetaryAmount, not that all MonetaryAmounts are income?

2022-03-30 23:51 UTC, jfgemski approved these changes

2022-03-31 00:28 UTC, rivettp reviewed
There seems to be many cases of subclassing MonetaryAmount which needs looking at. We are not consistent in this e.g. hasGrossIncome is a property which is what I'd expect. 
So I won't hold this up so long as we have the broader review. 
In general MonetaryAmount should in essence be treated as a (structured)datatype so should not be subclassed semantically like this.

2022-03-31 00:28 UTC, rivettp approved these changes

2022-03-31 01:42 UTC, merged