FND-365 - Wording for precious metals currency identifiers needs work
edmcouncil/fibo pull request #1759
Opened 2022-03-30 20:35 UTC by ElisaKendall

Signed-off-by: Elisa Kendall <ekendall@thematix.com>

## Description

 Revised currency codes to correct definitions for precious metals in the code generation process and added language tags

Fixes: #1721 / FND-365

## Checklist:

- [x] I'm familiar with the [FIBO developer quide](https://github.com/edmcouncil/fibo/blob/master/CONTRIBUTING.md#contributing-to-the-fibo-code). My contribution meets all the requirements described there.
- [x] My contribution follows the [principles of best practices for FIBO](https://github.com/edmcouncil/fibo/blob/master/ONTOLOGY_GUIDE.md).
- [x] My changes have been reconciled with latest master and no merge conflicts remain.
- [x] This PR is related to exactly one issue. The issue is referenced by using a GitHub keyword such as "fixes", "closes", or "resolves".
- [x] Hygiene tests have been applied by a PR with "(WIP)" in title.
- [x] The issue has been tested locally using a reasoner (for ontology changes).

2022-03-30 20:48 UTC, jfgemski submitted a review, later dismissed

2022-03-30 21:01 UTC, jfgemski approved these changes

2022-03-30 21:31 UTC, rivettp approved these changes
The glottal character for Paanga is wrong in the ISO source (and hence what I sent @ElisaKendall ) - however it should not be replaced by apostrophe but the character we painstakingly researched last time via Unicode database: Paʻanga

2022-03-30 21:34 UTC, rivettp requested changes
Actually the wording for the codes was not properly fixed, I'll have another go

2022-03-30 22:00 UTC, rivettp commented
Updated file provided to @ElisaKendall

2022-03-30 23:52 UTC, jfgemski approved these changes

2022-03-31 00:14 UTC, rivettp approved these changes

2022-03-31 00:22 UTC, merged