Hygine test update
edmcouncil/fibo pull request #2026
Opened 2024-06-27 13:28 UTC by mereolog

## Description

This pull request synchronises the FIBO hygiene tests with those in https://github.com/edmcouncil/idmp

## Checklist:

- [X] I'm familiar with the [FIBO developer quide](https://github.com/edmcouncil/fibo/blob/master/CONTRIBUTING.md#contributing-to-the-fibo-code). My contribution meets all the requirements described there.
- [X] My contribution follows the [principles of best practices for FIBO](https://github.com/edmcouncil/fibo/blob/master/ONTOLOGY_GUIDE.md).
- [X] My changes have been reconciled with latest master and no merge conflicts remain.
- [X] This PR is related to exactly one issue. The issue is referenced by using a GitHub keyword such as "fixes", "closes", or "resolves".
- [X] Hygiene tests have been applied by a PR with "(WIP)" in title.
- [X] The issue has been tested locally using a reasoner (for ontology changes).

2024-10-25 06:45 UTC, rivettp reviewed
Somewhere we should configure (and allow others to) which tests to be run against which project: I don't think we should assume that IDMP has the same requirements as FIBO. For example I don't think this one should apply to FIBO: etc/testing/hygiene_parameterized/testHygiene_performance_multiple_different_individuals.sparql

2024-11-15 06:22 UTC, ElisaKendall commented
> In a sense, we do have this option - whatever you put in the project's respective folder (/etc/testing/hygiene_parameterized) will be run, so if we do not want a test we can remove it from this folder.
> 
> The particular test you mentioned was explicitly requested by @ElisaKendall, so you should raise your concern with her - but I agree that it does not fit to this particular project.

I'm ok if you remove this one, but we just passed all of them so I don't see the harm in keeping it.

2024-12-30 07:33 UTC, ElisaKendall approved these changes
@mereolog -thank you!

2025-01-03 10:01 UTC, przemekgradzki requested changes

2025-01-03 19:30 UTC, przemekgradzki approved these changes

2025-01-03 20:23 UTC, ElisaKendall approved these changes

2025-01-03 20:23 UTC, merged